"""Precompute GENERATOR for Fig S7 (covariance-vs-correlation forward prediction).

The Fig S7 driver ``notebooks/src/run_figS7.py`` (and its notebook
``notebooks/suppl/figS7_covariance_correlation.ipynb``) globs a precompute tree

    <SUPPL>/precomputed_FULL_COV_FAST_FULLLOAD_CHUNKED/<dataset>__mean_ge_<tag>/

and for every folder reads (see ``run_figS7.process_one_folder``):

    genes.npy                    object array of gene names (length p)
    perturbations.npy            object array of perturbation labels (length n_perts)
    perturbation_stats.h5        dataset "dx" of shape (n_perts, p); optional "n_cells_pert"
    perturbation_target_map.tsv  columns {perturbation, target_gene}   (optional; improves matching)
    sigmas/Sigma_full_ridge.npy       true/full Sigma        (p x p)   -> TRUE_SIGMA_CANDIDATES[0]
    sigmas/Sigma_meanfield_ridge.npy  mean-field null Sigma  (p x p)   -> MEANFIELD_SIGMA_CANDIDATES[0]

The run module then WRITES the forward-score CSVs itself
(``cipher_forward_PEARSON_TRAINTEST_CORRCOORD_TRUE_AND_MF.csv`` and the
ORDINARY_CORRSPACE / ZONLY / HIGHVAR_FILTERED variants) from those base inputs, so this
generator only needs to produce the base per-folder inputs with the exact
names/dirs/columns above.

``tag`` = ``str(threshold).replace(".", "p")`` (matches ``suppl_covcorr.threshold_to_tag``).
Variants 1/2/3 and high-var config-2 read tag ``1p0`` (threshold 1.0); high-var config-1
reads tag ``0p1`` (threshold 0.1) -- so both thresholds are generated by default.

Everything is produced with the installed ``cipher`` package:
  * ``cipher.preprocess_dataset`` -> genes/perts/target_genes + Sigma_full_ridge + dx stats
  * ``cipher.meanfield_covariance`` -> the mean-field null Sigma (per-gene shuffle)

NOT part of the installable ``cipher`` package; a reproduction driver only.
"""
from __future__ import annotations

import os
import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd
import h5py

import cipher
from cipher.preprocess import (
    _materialize_cov_matrix,
    stable_seed,
    sanitize_filename,
)

# ----------------------------------------------------------------------------- config
DEFAULT_MODE = "raw"                 # dx + Sigma normalization; configurable
DEFAULT_THRESHOLDS = (1.0, 0.1)        # -> tags "1p0" and "0p1"
DEFAULT_GROUPS = ("CRISPRi", "CRISPRa")
PRECOMPUTE_SUBDIR = "precomputed_FULL_COV_FAST_FULLLOAD_CHUNKED"

TRUE_SIGMA_NAME = "Sigma_full_ridge.npy"
MEANFIELD_SIGMA_NAME = "Sigma_meanfield_ridge.npy"
SAVE_DTYPE = np.float32


def threshold_to_tag(x) -> str:
    """Match suppl_covcorr.threshold_to_tag exactly."""
    return str(x).replace(".", "p")


# ----------------------------------------------------------------------------- helpers
def _resolve_datasets(data_dir, datasets):
    data_dir = Path(data_dir)
    if datasets is not None:
        out = []
        for d in datasets:
            p = Path(d)
            if not p.is_absolute():
                name = d if str(d).endswith(".h5ad") else f"{d}.h5ad"
                p = data_dir / name
            out.append(p)
        return out

    hits = []
    for p in sorted(data_dir.glob("*.h5ad")):
        try:
            grp = cipher.dataset_group(p.stem)
        except Exception:
            grp = "unknown"
        if grp in DEFAULT_GROUPS:
            hits.append(p)
    return hits


def _copy(src, dst):
    """Hardlink when possible (saves disk for large Sigmas), else copy."""
    src, dst = Path(src), Path(dst)
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        dst.unlink()
    try:
        os.link(src, dst)
    except OSError:
        shutil.copy2(src, dst)


def _meanfield_sigma(data_path, threshold, mode, config, seed):
    """Mean-field (per-gene shuffled) null Sigma, on the SAME gene set / cov cells /
    normalization that preprocess_dataset used for the full Sigma, ridge-matched."""
    ds = cipher.load_dataset(
        str(data_path),
        expression_threshold=threshold,
        min_samples=config.min_samples_per_pert,
        cutoff_source=config.cutoff_source,
        only_single_gene=config.only_single_gene,
        require_target_in_var=config.require_target_in_var,
        force_include_targets=config.force_include_targets,
    )
    gene_names = np.asarray(ds.gene_names, dtype=object)

    control_raw = ds.control_matrix(dense=False)
    n_control = int(control_raw.shape[0])

    dataset_name = sanitize_filename(Path(data_path).stem)
    rng = np.random.default_rng(stable_seed(config.seed, dataset_name))
    if config.cov_max_cells is not None and n_control > config.cov_max_cells:
        sel = np.sort(rng.choice(n_control, int(config.cov_max_cells), replace=False))
        cov_raw = control_raw[sel]
    else:
        cov_raw = control_raw

    pc = ds.pflog_pseudocount if mode == "pflog" else None
    X_cov = _materialize_cov_matrix(cov_raw, mode, pc)

    S = np.asarray(cipher.meanfield_covariance(X_cov, seed=int(seed)), dtype=np.float64)
    ridge = float(config.ridge_abs)  # ridge_rel default 0 -> ridge == ridge_abs
    if ridge:
        di = np.diag_indices_from(S)
        S[di] = S[di] + ridge
    return S.astype(SAVE_DTYPE), gene_names


def _write_target_map(dest, staging_outdir):
    """perturbation_target_map.tsv from preprocess's aligned target_genes.npy."""
    perts_p = staging_outdir / "perturbations.npy"
    tgts_p = staging_outdir / "target_genes.npy"
    if not (perts_p.exists() and tgts_p.exists()):
        return None
    perts = np.load(perts_p, allow_pickle=True)
    tgts = np.load(tgts_p, allow_pickle=True)
    df = pd.DataFrame(
        {
            "perturbation": [str(x) for x in perts],
            "target_gene": [str(x) for x in tgts],
        }
    )
    out = dest / "perturbation_target_map.tsv"
    df.to_csv(out, sep="\t", index=False)
    return out


# ----------------------------------------------------------------------------- main API
def generate(
    data_dir,
    out_root,
    datasets=None,
    thresholds=DEFAULT_THRESHOLDS,
    mode=DEFAULT_MODE,
    seed=0,
    overwrite=False,
):
    """Produce the Fig S7 base precompute tree under ``out_root``.

    Parameters
    ----------
    data_dir : str | Path
        Directory of base Perturb-seq ``.h5ad`` files (``$CIPHER_DATA_DIR``).
    out_root : str | Path
        The precompute root the consumer globs, i.e.
        ``<SUPPL>/precomputed_FULL_COV_FAST_FULLLOAD_CHUNKED``. (If you point it at
        ``<SUPPL>`` this function still writes to ``out_root`` verbatim, so pass the
        CHUNKED dir itself.)
    datasets : list[str] | None
        Dataset stems / paths. ``None`` -> glob ``data_dir/*.h5ad`` filtered by
        ``cipher.dataset_group in {CRISPRi, CRISPRa}``.
    thresholds : iterable of float
        Expression thresholds -> one folder tag each. Default (1.0, 0.1).
    mode : str
        Normalization mode for dx + Sigma (a key of cipher.NORMALIZATION_MODES).
    """
    out_root = Path(out_root)
    out_root.mkdir(parents=True, exist_ok=True)
    staging_root = out_root / "_staging"
    staging_root.mkdir(parents=True, exist_ok=True)

    paths = _resolve_datasets(data_dir, datasets)
    print(f"[gen] datasets={len(paths)} thresholds={list(thresholds)} mode={mode}")
    for p in paths:
        print(f"       - {p.name}")

    produced, errors = [], []

    for threshold in thresholds:
        tag = threshold_to_tag(threshold)
        config = cipher.PreprocessConfig(
            expression_threshold=float(threshold),
            cutoff_source="control",
            save_mean_var=True,
            seed=int(seed),
        )
        for data_path in paths:
            data_path = Path(data_path)
            dataset_name = sanitize_filename(data_path.stem)
            dest = out_root / f"{dataset_name}__mean_ge_{tag}"
            sig_dest = dest / "sigmas"

            done_marker = [
                dest / "genes.npy",
                dest / "perturbations.npy",
                dest / "perturbation_stats.h5",
                sig_dest / TRUE_SIGMA_NAME,
                sig_dest / MEANFIELD_SIGMA_NAME,
            ]
            if not overwrite and all(x.exists() for x in done_marker):
                print(f"[skip] {dest.name} (complete)")
                produced.append(str(dest))
                continue

            try:
                if not data_path.exists():
                    raise FileNotFoundError(str(data_path))

                # 1) base precompute (genes/perts/targets + Sigma_full_ridge + dx stats)
                staging_outdir = cipher.preprocess_dataset(
                    str(data_path),
                    str(staging_root),
                    modes=[mode],
                    config=config,
                    overwrite=overwrite,
                )
                staging_outdir = Path(staging_outdir)
                mode_dir = staging_outdir / "normalizations" / mode

                sig_dest.mkdir(parents=True, exist_ok=True)

                # 2) dataset-level files (exact names/order the consumer reads)
                _copy(staging_outdir / "genes.npy", dest / "genes.npy")
                _copy(staging_outdir / "perturbations.npy", dest / "perturbations.npy")
                _copy(mode_dir / "perturbation_stats.h5", dest / "perturbation_stats.h5")
                _copy(mode_dir / "Sigma_full_ridge.npy", sig_dest / TRUE_SIGMA_NAME)
                _write_target_map(dest, staging_outdir)

                # 3) mean-field null Sigma (same gene set / cov cells / normalization)
                S_mf, mf_genes = _meanfield_sigma(data_path, threshold, mode, config, seed)
                genes = np.load(dest / "genes.npy", allow_pickle=True)
                if len(mf_genes) != len(genes):
                    raise ValueError(
                        f"mean-field gene count {len(mf_genes)} != full gene count {len(genes)}"
                    )
                np.save(sig_dest / MEANFIELD_SIGMA_NAME, S_mf)

                # 4) sanity: dx shape must be (n_perts, p)
                perts = np.load(dest / "perturbations.npy", allow_pickle=True)
                with h5py.File(dest / "perturbation_stats.h5", "r") as h5:
                    dx_shape = h5["dx"].shape
                if dx_shape != (len(perts), len(genes)):
                    raise ValueError(
                        f"dx shape {dx_shape} != (n_perts={len(perts)}, p={len(genes)})"
                    )

                print(f"[ok]   {dest.name}  p={len(genes)} n_perts={len(perts)}")
                produced.append(str(dest))

            except Exception as e:  # noqa: BLE001
                print(f"[ERROR] {dataset_name} tag={tag}: {e!r}")
                errors.append({"dataset": dataset_name, "tag": tag, "error": repr(e)})

    manifest = {
        "out_root": str(out_root),
        "mode": mode,
        "thresholds": [float(t) for t in thresholds],
        "n_produced": len(produced),
        "produced": produced,
        "errors": errors,
    }
    with open(out_root / "_gen_fullcov_scores_manifest.json", "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"[gen] done: {len(produced)} folders, {len(errors)} errors")
    return manifest


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--data-dir", default=os.environ.get("CIPHER_DATA_DIR"))
    ap.add_argument(
        "--out-root",
        default=os.path.join(
            os.environ.get("CIPHER_DATA_DIR", "."), "suppl", PRECOMPUTE_SUBDIR
        ),
    )
    ap.add_argument("--datasets", nargs="*", default=None)
    ap.add_argument("--mode", default=DEFAULT_MODE)
    ap.add_argument("--thresholds", nargs="*", type=float, default=list(DEFAULT_THRESHOLDS))
    ap.add_argument("--overwrite", action="store_true")
    args = ap.parse_args()

    generate(
        data_dir=args.data_dir,
        out_root=args.out_root,
        datasets=args.datasets,
        thresholds=tuple(args.thresholds),
        mode=args.mode,
        overwrite=args.overwrite,
    )
